# Generated by Django 5.0.6 on 2024-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=14)),
                ('speed', models.CharField(max_length=200)),
                ('POP_name', models.CharField(max_length=400)),
                ('DSLAM_hostname', models.CharField(max_length=200)),
                ('frame', models.CharField(max_length=200)),
            ],
        ),
    ]
